# Network config for Archlinux
#
# This should work for every systemd powered system
- mtu: "1492"

- set_hostname:
  - exec_in: echo $$hostname > /etc/hostname

- set_host:
  - write_in:
    - /etc/hosts
    - |
      127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4 $$hostname
      ::1         localhost localhost.localdomain localhost6 localhost6.localdomain6 $$hostname

- set_interface:
  - write_in:
    - /etc/sysconfig/network-scripts/ifcfg-eth0
    - |
      DEVICE="eth0"
      BOOTPROTO=dhcp
      NM_CONTROLLED="no"
      PERSISTENT_DHCLIENT=1
      ONBOOT="yes"
      TYPE=Ethernet
      DEFROUTE=yes
      PEERDNS=yes
      PEERROUTES=yes
      IPV4_FAILURE_FATAL=yes
      IPV6INIT=yes
      IPV6_AUTOCONF=yes
      IPV6_DEFROUTE=yes
      IPV6_PEERDNS=yes
      IPV6_PEERROUTES=yes
      IPV6_FAILURE_FATAL=no
      NAME="eth0"
      MTU=$$mtu
  - write_out:
    - $$rootfs/etc/sysconfig/network
    - |
      #
      HOSTNAME=$$hostname

- enable_network:
  - exec_in: systemctl disable NetworkManager.service  2>&1
  - exec_in: chkconfig network on
  - exec_in: systemctl enable network.service  2>&1
