# Keyboard configuration

- set_keyboard_layout:
  - write_in:
    - /etc/vconsole.conf
    - |
      KEYMAP=$$layout
  - exec_in: loadkeys $$layout
  - write_in:
    - /etc/sysconfig/keyboard
    - |
      KEYTABLE=$$layout
